### ISSUE TITLE
Not working any more...

### ISSUE THREAD

**Issue by theZMan** [nishnet2002/Safeway-Just-for-u#1]
Looks like after 3 years safeway changed something - doesn't seem to be working any more.. sad times.

**Comment by nishnet2002** [comment]
Hi @theZMan,

Thanks for reporting. I haven't been using this script for long time or maintaining. I will not able to commit more time to this.

**Comment by theZMan** [comment]
I figured as much... do you happen to have an unminified version of the bookmark anywhere?

**Comment by nishnet2002** [comment]
Here you go: https://github.com/nishnet2002/Safeway-Just-for-u/blob/master/couponclipper.user.js

**Comment by theZMan** [comment]
Thanks - looks like they changed a few things.. I'll send you some fixes..

**Comment by Raybot2** [comment]
I would love to see this fixed! Please post it here if you guys fix it. Much appreciated!

**Comment by kton** [comment]
Did a quick patch and it seems to be working, see commit for the changes:  https://github.com/kton/Safeway-Just-for-u/commit/7aefad871ff39d2d70dae8ea2e9fbb5ef7ccdf0d

Can't really test it further since my initial attempt clipped all the coupons.

https://github.com/kton/Safeway-Just-for-u

![output](https://cloud.githubusercontent.com/assets/6096547/24851763/c960e48e-1d89-11e7-9cc3-0e4f05e0d119.gif)

**Comment by nishnet2002** [comment]
@kton, Thanks for fix. I'll test it out.

**Comment by jdclark73** [comment]
@kton I tried your new one at https://github.com/kton/Safeway-Just-for-u, and as you describe, there is a difference now between adding to card and adding to list. The way you have it is that it adds to the card but not the list, in order to keep the list uncluttered. In old versions of the app it showed you if it was on the card, but not the list, but my version (latest Android version of app) it doesn't show that. Could you make a second bookmarklet option that just adds to the list? I don't use the list anyway so wouldn't be bothered by it. In effect, from what you say, it should work now anyway, even if it doesn't show as added. So I guess this is more just so I have a visual cue that it's added. Note: haven't added this as an issue on your fork because issues seem to be disabled

**Comment by kton** [comment]
@jcgtzkn I've enabled issues and created a new default branch (safeway-nimbus) that provides the visual cues you're looking for. I've only tested it on the latest Chrome stable build, though.

The master branch is still present in case anyone is looking for the old functionality.

**Comment by jdclark73** [comment]
@kton thanks! Meant to post earlier to confirm that it's working. Been using it successfully for a while now
